GET http://localhost:8000/libros HTTP/1.1

###

GET http://localhost:8000/libros/2 HTTP/1.1


###

POST http://localhost:8000/libros HTTP/1.1
Content-Type: application/json

{
    "title": "The",
    "author": "J.D. Salinger",
    "publish_year": 1951

}

###

PUT http://localhost:8000/libros/3 HTTP/1.1
Content-Type: application/json

{
    "publish_year": 1964
}

###

DELETE  http://localhost:8000/libros/6 HTTP/1.1